global:
  scrape_interval:     15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - static_configs:
    - targets:

rule_files:

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node_exporter'

    static_configs:
    - targets: ['localhost:9100']

  - job_name: 'promtrail'

    static_configs:
    - targets: ['localhost:3100']

